//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.CG {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMS.CG.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 radians degrees
        ///sin cos tan
        ///asin acos atan
        ///sinh cosh tanh
        ///asinh acosh atanh
        ///pow exp log exp2 log2
        ///sqrt inversesqrt
        ///abs sign floor trunc round roundEven ceil fract mod modf
        ///min max clamp mix step smoothstep
        ///isnan isinf
        ///floatBitsToInt floatBitsToUint
        ///intBitsToFloat uintBitsToFloat
        ///fma frexp ldexp
        ///packUnorm2x16 packSnorm2x16 packUnorm4x8 packSnorm4x8
        ///unpackUnorm2x16 unpackSnorm2x16 unpackUnorm4x8 unpackSnorm4x8
        ///packDouble2x32
        ///unpackDouble2x32
        ///packHalf2x16
        ///unpackHalf2x16
        ///length distance dot c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cgFunctions {
            get {
                return ResourceManager.GetString("cgFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 attribute const
        ///uniform varying buffer shared
        ///coherent volatile restrict readonly writeonly
        ///atomic_uint
        ///layout quads equal_spacing fractional_even_spacing fractional_odd_spacing cw ccw points
        ///centroid flat smooth noperspective
        ///patch sample
        ///break continue do for while switch case default
        ///if else
        ///subroutine
        ///in out
        ///inout
        ///float double int void
        ///bool
        ///true false
        ///invariant precise
        ///discard return
        ///lowp mediump highp precision
        ///
        ///mat2 mat3 mat4 dmat2 dmat3 dmat4
        ///mat2x2 mat2x3 mat2x4 dmat2x2 dmat2x3 d [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cgKeywords {
            get {
                return ResourceManager.GetString("cgKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gl_NumWorkGroups
        ///gl_WorkGroupSize
        ///gl_WorkGroupID
        ///gl_LocalInvocationID
        ///gl_GlobalInvocationID
        ///gl_LocalInvocationIndex
        ///gl_LocalGroupSizeARB
        ///
        ///gl_VertexID
        ///gl_VertexIndex
        ///gl_InstanceID
        ///gl_InstanceIndex
        ///gl_PerVertex
        ///gl_Position
        ///gl_PointSize
        ///gl_ClipDistance
        ///gl_CullDistance
        ///gl_in
        ///gl_out
        ///
        ///gl_PrimitiveIDIn
        ///gl_InvocationID
        ///
        ///gl_PrimitiveID
        ///gl_Layer
        ///gl_ViewportIndex
        ///
        ///gl_PatchVerticesIn
        ///gl_PrimitiveID
        ///gl_InvocationID
        ///
        ///gl_TessLevelOuter
        ///gl_TessLevelInner
        ///
        ///gl_PatchVerticesIn
        ///gl_PrimitiveID [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cgVariables {
            get {
                return ResourceManager.GetString("cgVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright 2016 DMS
        ///
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at
        ///
        ///    http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        ///See the License for the specific language governing perm [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
    }
}
